name: app_tim_viec_lam
description: "A new Flutter project."
# Ngăn không cho package được publish lên pub.dev, xóa dòng này nếu bạn muốn publish
publish_to: 'none'

# Định nghĩa phiên bản và build number cho ứng dụng
version: 1.0.0+1

# Yêu cầu phiên bản SDK
environment:
  sdk: ^3.7.0

# Các package mà ứng dụng của bạn phụ thuộc
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0  # Package để thực hiện các yêu cầu HTTP
  cupertino_icons: ^1.0.8  # Font icon kiểu iOS

# Các package chỉ sử dụng trong quá trình phát triển/test
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Bộ lint khuyến nghị cho coding practices

# Cấu hình đặc biệt cho Flutter
flutter:
  # Kích hoạt Material Icons font
  uses-material-design: true

  # Thêm assets (hình ảnh, file tĩnh) nếu cần
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Thêm font tùy chỉnh nếu cần
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700